language: cpp
sudo: true

notifications:
  email: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - eval "CC=g++6 && CXX=g++7"

script:
  - chmod 777 ./cpplint.py
  - ( for file in $(find ./ -name "*.cpp"); do ./cpplint.py $file || exit; done );
  - mkdir build && cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES .. && make
  - ( for file in $(find ../ -name "*.cpp"); do echo $file; clang-check -analyze $file -p ./ || exit; done );
  - ./executable
